apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: test-webhook
webhooks:
  - sideEffects: None
    admissionReviewVersions:
      - v1
      - v1beta1
    name: test-webhook.default.svc.cluster.local
    clientConfig:
      service:
        name: test-webhook
        namespace: default
        path: "/oversold"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvekNDQW91Z0F3SUJBZ0lVWWpMSEEvcHJobUhEY0pJZjN2MFBYdjdvREEwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qUXdPREEzCk1ESTFPVEF3V2hjTk1qa3dPREEyTURJMU9UQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNYUZQS3NxClFySTUrSlBNSDkzeTVQUmk1Um5OQ1o5RHZUakcxRWhmaHUvcHJBZkFYVFErdjZINmpSNmNPR2ZOVFJ0UlBpbTEKY3lvMjZDWUN3eE5KY3RLMkRjYk4xdFcrS1FwQTlES3ppUHN0S3hxU3MzdUptaWwvN1dDSWQvS1FsOXhieUtucAo5WENPZG9wV3BNWCtpaXd2c3Fsazd0RWczOXdxLzNZakVrNFphbGNyRXNYdWJMUlRVZmkva0NuNUpuemt0aE9GCnNhVnVxOXJGYno4VXJ4STJCRVZvdDVmTTFHV2g1bTJ3b2hMdXluS2M1RGp4dnFDNFVDbHFmdXlGaFZWMjBEcWMKVUcrcUR2Z1VSRS9hRHFOelY5V1NhZytvTThpRFF3ZTF4R3M2eEhldmhINGlsSVQ2MkFsVDlXWEVXUi9HRitUNApiTUgrOVBYZnZIZVNobmNDQXdFQUFhTnhNRzh3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRkZ5a1dkczFzdEJUMkdLLzhuSTljL0wvdmxLa01DMEdBMVVkRVFRbU1DU0gKQkg4QUFBR0hCQXAwaWNTSEJBcDBVaHlIQkFwMEpEbUhCQXIrQUFHSEJLd2NDSWN3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFHaWNMdWlKNHRiNzVGTFIrU2p5ZmtjNDBCUzFTRVB0TXdidFJuOEx2M2s3VUN6bTZKSTBqY0dFCkVZQmRLQlAzalNuUTRGNDNOTnJLMDRlRVJldFg1RTJJYWRrRGRGM29MSlJndHZNRVd0WStSMjRqM3RTZ1d2akMKUEY5N09zZnZsSnFQWG9NNVQwbUw5dTRuZDRUTUpwVG9qVnZiQkg5K3R3cFI4YnJ4bUk2MVdZcjdLTk1qNzR5bQp6SWRUTllUMnM4Z21GTjY2YSswWTVFc3pyK0luMmNmT1Vwako4aDVNbFYxdVlhd05KbENaUmlCNzk1NnNORTh6CnA5RjJMMzFicmNrVCsxK1ozZGtFSTNranhKdDdoWnFscXBlRHdYQWxnbHVydDgwR1p0T0U4Z1Q3bzRMSUp3MEkKNTdsZldIZzFheG9PSENIb1NGa0hnSmlHR215RmpIST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - operations: [ "UPDATE" ]
        apiGroups: [ "*" ]
        apiVersions: [ "v1" ]
        resources: [ "nodes/status"]